(define (pascal depth n)
  (cond ((= n 1) 1)
        ((< n 1) 0)
        ((= n depth) 1)
        ((> n depth) 0)
        (:else (+ (pascal (- depth 1) (- n 1))
                  (pascal (- depth 1) n)))))

(define (print-pascal depth)
  (define (iter i)
     (print-row i)
     (if (>= i depth)
         '() 
         (iter (+ i 1))))
   (iter 1))

(define (print-row depth)
  (define (iter n)
    (display (pascal depth n))
    (display " ")
    (if (>= n depth)
        (display "\n")
        (iter (+ n 1))))
  (iter 1))

